FROM ubuntu:20.04

LABEL maintainer="Matheus Tavares"

RUN apt-get -y update 

RUN apt-get install -y curl locales tzdata \
    && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 \
    && echo "America/Cuiaba" > /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata

RUN apt-get -y update 

RUN apt-get install -y git python3.8 python3-pip
RUN apt-get install -y firefox xvfb 

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get install -y wkhtmltopdf

ENV LANG en_US.utf8
ENV DEFAULT=/Defesa-Reports

RUN git clone https://github.com/s0berano/Defesa-Reports.git

WORKDIR ${DEFAULT}

ADD token.txt ${DEFAULT}

RUN pip3 install -r requirements.txt 

CMD [ "python3", "./run.py" ]

EXPOSE 443